#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Render every myeyes implementation from `theme.toml`.

    tools/build.py              # regenerate all targets inside the repo
    tools/build.py --check      # exit 1 if any generated file is stale
    tools/build.py --install    # also copy extras to their dotfile locations

Outputs (all committed, so the repo works without running this):

    colors/myeyes.lua                     Neovim colorscheme (repo is a plugin)
    lua/lualine/themes/myeyes.lua         lualine theme
    extras/tmux/myeyes.conf               tmux status/border/message colours
    extras/fish/myeyes.theme              fish syntax-highlighting theme
    extras/fzf/myeyes.opts                fzf colours (FZF_DEFAULT_OPTS_FILE)
    extras/codex/myeyes.tmTheme           Codex CLI syntax theme (also bat/Sublime)
    extras/claude/myeyes.json             Claude Code custom theme
    extras/windows-terminal/myeyes.json   Windows Terminal colour scheme
    extras/alacritty/myeyes.toml          Alacritty colours

Every target reads *roles* (`ui.fg`, `syntax.keyword`, `ansi.red`, ...), never
palette names directly, so changing which colour a role uses in `theme.toml`
is reflected everywhere after a rebuild.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

from myeyes_theme import Theme, load_theme

REPO = Path(__file__).resolve().parent.parent
HEADER = "Generated by tools/build.py from theme.toml. Do not edit by hand."


@dataclass(frozen=True)
class Output:
    path: str  # relative to the repo root
    content: str


def hx(theme: Theme, role: str) -> str:
    """Resolve a role (`"ui.fg"`) to hex. `"palette.<name>"` reaches a palette
    entry directly, for the rare program-specific colour no role describes
    (e.g. Claude's brand accent and its shimmer)."""
    if role.startswith("palette."):
        return theme.palette[role.removeprefix("palette.")].hex
    return theme.role(role).hex


# ==============================================================================
# Neovim colorscheme
# ==============================================================================

# Highlight specs are written as Python dicts whose colour values are role
# names; `_nvim_spec` resolves them to hex. `link` passes through unchanged.
#
# Styles (bold, undercurl, ...) live here rather than in `theme.toml`, because
# the definition currently only describes colours. Comments are deliberately
# *not* italic: the previous gruvbox setup disabled italic comments.
# TODO: move styles into theme.toml if a second target ever needs them.

NVIM_GROUPS: dict[str, dict] = {
    # --- Editor chrome -------------------------------------------------------
    "Normal": {"fg": "ui.fg", "bg": "ui.bg"},
    "NormalNC": {"link": "Normal"},
    "NormalFloat": {"fg": "ui.fg", "bg": "ui.float"},
    "FloatBorder": {"fg": "ui.float_border", "bg": "ui.float"},
    "FloatTitle": {"fg": "ui.fg_strong", "bg": "ui.float", "bold": True},
    "Cursor": {"fg": "ui.cursor_text", "bg": "ui.cursor"},
    "lCursor": {"link": "Cursor"},
    "CursorIM": {"link": "Cursor"},
    "TermCursor": {"link": "Cursor"},
    "CursorLine": {"bg": "ui.cursorline"},
    "CursorColumn": {"bg": "ui.cursorline"},
    "ColorColumn": {"bg": "ui.cursorline"},
    "CursorLineNr": {"fg": "ui.line_number_active", "bold": True},
    "LineNr": {"fg": "ui.line_number"},
    "SignColumn": {"fg": "ui.line_number"},
    "FoldColumn": {"fg": "ui.line_number"},
    "Folded": {"fg": "ui.fg_muted", "bg": "ui.cursorline"},
    "WinSeparator": {"fg": "ui.border"},
    "VertSplit": {"link": "WinSeparator"},
    "StatusLine": {"fg": "ui.fg", "bg": "ui.statusline"},
    "StatusLineNC": {"fg": "ui.fg_muted", "bg": "ui.statusline"},
    "TabLine": {"fg": "ui.fg_muted", "bg": "ui.statusline"},
    "TabLineFill": {"bg": "ui.statusline"},
    "TabLineSel": {"fg": "ui.fg_strong", "bg": "ui.bg", "bold": True},
    "WinBar": {"fg": "ui.fg", "bold": True},
    "WinBarNC": {"fg": "ui.fg_muted"},
    "Pmenu": {"fg": "ui.fg", "bg": "ui.float"},
    "PmenuSel": {"fg": "ui.selection_fg", "bg": "ui.selection"},
    "PmenuSbar": {"bg": "ui.float"},
    "PmenuThumb": {"bg": "ui.border"},
    "PmenuKind": {"fg": "syntax.type", "bg": "ui.float"},
    "PmenuExtra": {"fg": "ui.fg_muted", "bg": "ui.float"},
    "Visual": {"bg": "ui.selection"},
    "VisualNOS": {"link": "Visual"},
    "Search": {"bg": "ui.search"},
    "CurSearch": {"bg": "ui.search_current", "bold": True},
    "IncSearch": {"link": "CurSearch"},
    "Substitute": {"link": "CurSearch"},
    "MatchParen": {"bg": "ui.match_paren", "bold": True},
    "NonText": {"fg": "ui.fg_subtle"},
    "Whitespace": {"fg": "ui.border"},
    "SpecialKey": {"fg": "ui.fg_subtle"},
    "EndOfBuffer": {"fg": "ui.bg"},
    "Conceal": {"fg": "ui.fg_muted"},
    "Directory": {"fg": "syntax.function"},
    "Title": {"fg": "ui.fg_strong", "bold": True},
    "Question": {"fg": "diagnostic.info"},
    "MoreMsg": {"fg": "diagnostic.info"},
    "ModeMsg": {"fg": "ui.fg_strong", "bold": True},
    "MsgArea": {"fg": "ui.fg"},
    "ErrorMsg": {"fg": "diagnostic.error", "bold": True},
    "WarningMsg": {"fg": "diagnostic.warning"},
    "WildMenu": {"link": "PmenuSel"},
    "QuickFixLine": {"bg": "ui.selection", "bold": True},
    "SpellBad": {"sp": "diagnostic.error", "undercurl": True},
    "SpellCap": {"sp": "diagnostic.warning", "undercurl": True},
    "SpellLocal": {"sp": "diagnostic.info", "undercurl": True},
    "SpellRare": {"sp": "diagnostic.hint", "undercurl": True},
    # --- Diff ------------------------------------------------------------------
    "DiffAdd": {"bg": "diagnostic.diff_add_bg"},
    "DiffDelete": {"fg": "diagnostic.diff_delete", "bg": "diagnostic.diff_delete_bg"},
    "DiffChange": {"bg": "diagnostic.diff_change_bg"},
    "DiffText": {"bg": "diagnostic.diff_change_word_bg"},
    "Added": {"fg": "diagnostic.diff_add"},
    "Removed": {"fg": "diagnostic.diff_delete"},
    "Changed": {"fg": "diagnostic.diff_change"},
    "diffAdded": {"link": "Added"},
    "diffRemoved": {"link": "Removed"},
    "diffChanged": {"link": "Changed"},
    "diffFile": {"fg": "ui.fg_strong", "bold": True},
    "diffLine": {"fg": "syntax.function"},
    "diffIndexLine": {"fg": "ui.fg_muted"},
    # --- Legacy syntax groups (used by non-treesitter filetypes) --------------
    "Comment": {"fg": "syntax.comment"},
    "Constant": {"fg": "syntax.constant"},
    "String": {"fg": "syntax.string"},
    "Character": {"link": "String"},
    "Number": {"fg": "syntax.number"},
    "Boolean": {"fg": "syntax.boolean"},
    "Float": {"link": "Number"},
    "Identifier": {"fg": "syntax.variable"},
    "Function": {"fg": "syntax.function"},
    "Statement": {"fg": "syntax.keyword"},
    "Conditional": {"fg": "syntax.keyword_control"},
    "Repeat": {"fg": "syntax.keyword_control"},
    "Label": {"fg": "syntax.keyword_control"},
    "Operator": {"fg": "syntax.operator"},
    "Keyword": {"fg": "syntax.keyword"},
    "Exception": {"fg": "syntax.keyword_control"},
    "PreProc": {"fg": "syntax.macro"},
    "Include": {"fg": "syntax.keyword"},
    "Define": {"fg": "syntax.macro"},
    "Macro": {"fg": "syntax.macro"},
    "PreCondit": {"fg": "syntax.macro"},
    "Type": {"fg": "syntax.type"},
    "StorageClass": {"fg": "syntax.storage"},
    "Structure": {"fg": "syntax.keyword"},
    "Typedef": {"fg": "syntax.keyword"},
    "Special": {"fg": "syntax.escape"},
    "SpecialChar": {"fg": "syntax.escape"},
    "Tag": {"fg": "syntax.function"},
    "Delimiter": {"fg": "syntax.punctuation"},
    "SpecialComment": {"fg": "syntax.comment", "bold": True},
    "Debug": {"fg": "diagnostic.warning"},
    "Underlined": {"fg": "ui.link", "underline": True},
    "Ignore": {"fg": "ui.fg_subtle"},
    "Error": {"fg": "diagnostic.error", "bold": True},
    "Todo": {"fg": "ui.fg_strong", "bg": "ui.search", "bold": True},
    # --- Tree-sitter captures --------------------------------------------------
    "@variable": {"fg": "syntax.variable"},
    "@variable.builtin": {"fg": "syntax.keyword"},  # self, this
    "@variable.parameter": {"fg": "syntax.parameter"},
    "@variable.member": {"fg": "syntax.field"},
    "@property": {"fg": "syntax.field"},
    "@constant": {"fg": "syntax.constant"},
    "@constant.builtin": {"fg": "syntax.constant"},
    "@constant.macro": {"fg": "syntax.macro"},
    "@module": {"fg": "syntax.module"},
    "@module.builtin": {"fg": "syntax.module"},
    # Rust lifetimes are captured as @label by nvim-treesitter.
    "@label": {"fg": "syntax.lifetime"},
    "@string": {"fg": "syntax.string"},
    "@string.escape": {"fg": "syntax.escape"},
    "@string.special": {"fg": "syntax.escape"},
    "@string.regexp": {"fg": "syntax.escape"},
    "@string.special.url": {"fg": "ui.link", "underline": True},
    "@character": {"fg": "syntax.string"},
    "@character.special": {"fg": "syntax.escape"},
    "@number": {"fg": "syntax.number"},
    "@number.float": {"fg": "syntax.number"},
    "@boolean": {"fg": "syntax.boolean"},
    "@type": {"fg": "syntax.type"},
    "@type.builtin": {"fg": "syntax.type_builtin"},
    "@type.definition": {"fg": "syntax.type"},
    "@attribute": {"fg": "syntax.attribute"},
    "@attribute.builtin": {"fg": "syntax.attribute"},
    "@function": {"fg": "syntax.function"},
    "@function.builtin": {"fg": "syntax.function_call"},
    "@function.call": {"fg": "syntax.function_call"},
    "@function.macro": {"fg": "syntax.macro"},
    "@function.method": {"fg": "syntax.function"},
    "@function.method.call": {"fg": "syntax.function_call"},
    "@constructor": {"fg": "syntax.type"},
    "@operator": {"fg": "syntax.operator"},
    "@keyword": {"fg": "syntax.keyword"},
    "@keyword.coroutine": {"fg": "syntax.keyword_control"},
    "@keyword.function": {"fg": "syntax.keyword"},
    "@keyword.operator": {"fg": "syntax.keyword"},
    "@keyword.import": {"fg": "syntax.keyword"},
    "@keyword.type": {"fg": "syntax.keyword"},
    "@keyword.modifier": {"fg": "syntax.storage"},
    "@keyword.repeat": {"fg": "syntax.keyword_control"},
    "@keyword.return": {"fg": "syntax.keyword_control"},
    "@keyword.conditional": {"fg": "syntax.keyword_control"},
    "@keyword.exception": {"fg": "syntax.keyword_control"},
    "@keyword.directive": {"fg": "syntax.macro"},
    "@punctuation.delimiter": {"fg": "syntax.punctuation"},
    "@punctuation.bracket": {"fg": "syntax.punctuation"},
    "@punctuation.special": {"fg": "syntax.escape"},
    "@comment": {"fg": "syntax.comment"},
    "@comment.documentation": {"fg": "syntax.comment"},
    "@comment.error": {"fg": "diagnostic.error", "bold": True},
    "@comment.warning": {"fg": "diagnostic.warning", "bold": True},
    "@comment.todo": {"link": "Todo"},
    "@comment.note": {"fg": "diagnostic.info", "bold": True},
    "@markup.heading": {"fg": "ui.fg_strong", "bold": True},
    "@markup.strong": {"bold": True},
    "@markup.italic": {"italic": True},
    "@markup.strikethrough": {"strikethrough": True},
    "@markup.underline": {"underline": True},
    "@markup.quote": {"fg": "ui.fg_muted"},
    "@markup.math": {"fg": "syntax.number"},
    "@markup.link": {"fg": "ui.link"},
    "@markup.link.label": {"fg": "ui.link"},
    "@markup.link.url": {"fg": "ui.link", "underline": True},
    "@markup.raw": {"fg": "syntax.string"},
    "@markup.list": {"fg": "syntax.punctuation"},
    "@markup.list.checked": {"fg": "diagnostic.ok"},
    "@markup.list.unchecked": {"fg": "ui.fg_muted"},
    "@diff.plus": {"link": "Added"},
    "@diff.minus": {"link": "Removed"},
    "@diff.delta": {"link": "Changed"},
    "@tag": {"fg": "syntax.keyword"},
    "@tag.builtin": {"fg": "syntax.keyword"},
    "@tag.attribute": {"fg": "syntax.attribute"},
    "@tag.delimiter": {"fg": "syntax.punctuation"},
    # --- LSP semantic tokens -----------------------------------------------------
    # rust-analyzer's semantic tokens override tree-sitter, so the important
    # ones map back onto the same roles. Unlisted tokens fall through to
    # Neovim's default links (mostly onto the tree-sitter groups above).
    "@lsp.type.lifetime": {"fg": "syntax.lifetime"},
    "@lsp.type.macro": {"fg": "syntax.macro"},
    "@lsp.type.decorator": {"fg": "syntax.attribute"},
    "@lsp.type.attributeBracket": {"fg": "syntax.attribute"},
    "@lsp.type.builtinAttribute": {"fg": "syntax.attribute"},
    "@lsp.type.derive": {"fg": "syntax.attribute"},
    "@lsp.type.namespace": {"fg": "syntax.module"},
    "@lsp.type.enumMember": {"fg": "syntax.constant"},
    "@lsp.type.typeParameter": {"fg": "syntax.type"},
    "@lsp.type.selfKeyword": {"fg": "syntax.keyword"},
    "@lsp.type.selfTypeKeyword": {"fg": "syntax.keyword"},
    "@lsp.type.keyword": {"fg": "syntax.keyword"},
    "@lsp.type.formatSpecifier": {"fg": "syntax.escape"},
    "@lsp.type.escapeSequence": {"fg": "syntax.escape"},
    "@lsp.type.unresolvedReference": {"sp": "diagnostic.error", "undercurl": True},
    "@lsp.mod.constant": {"fg": "syntax.constant"},
    "@lsp.typemod.function.defaultLibrary": {"fg": "syntax.function_call"},
    # --- Diagnostics -------------------------------------------------------------
    "DiagnosticError": {"fg": "diagnostic.error"},
    "DiagnosticWarn": {"fg": "diagnostic.warning"},
    "DiagnosticInfo": {"fg": "diagnostic.info"},
    "DiagnosticHint": {"fg": "diagnostic.hint"},
    "DiagnosticOk": {"fg": "diagnostic.ok"},
    "DiagnosticVirtualTextError": {"fg": "diagnostic.error", "bg": "diagnostic.error_bg"},
    "DiagnosticVirtualTextWarn": {"fg": "diagnostic.warning", "bg": "diagnostic.warning_bg"},
    "DiagnosticVirtualTextInfo": {"fg": "diagnostic.info", "bg": "diagnostic.info_bg"},
    "DiagnosticVirtualTextHint": {"fg": "diagnostic.hint", "bg": "diagnostic.hint_bg"},
    "DiagnosticUnderlineError": {"sp": "diagnostic.error", "undercurl": True},
    "DiagnosticUnderlineWarn": {"sp": "diagnostic.warning", "undercurl": True},
    "DiagnosticUnderlineInfo": {"sp": "diagnostic.info", "undercurl": True},
    "DiagnosticUnderlineHint": {"sp": "diagnostic.hint", "undercurl": True},
    "DiagnosticUnnecessary": {"fg": "ui.fg_subtle"},
    "DiagnosticDeprecated": {"strikethrough": True},
    "LspReferenceText": {"bg": "ui.selection"},
    "LspReferenceRead": {"bg": "ui.selection"},
    "LspReferenceWrite": {"bg": "ui.selection", "bold": True},
    "LspInlayHint": {"fg": "ui.fg_subtle", "bg": "ui.cursorline"},
    "LspCodeLens": {"fg": "ui.fg_subtle"},
    "LspSignatureActiveParameter": {"bg": "ui.selection", "bold": True},
    # --- Plugins in use --------------------------------------------------------
    # gitsigns
    "GitSignsAdd": {"fg": "diagnostic.diff_add"},
    "GitSignsChange": {"fg": "diagnostic.diff_change"},
    "GitSignsDelete": {"fg": "diagnostic.diff_delete"},
    # telescope
    "TelescopeNormal": {"link": "NormalFloat"},
    "TelescopeBorder": {"link": "FloatBorder"},
    "TelescopeTitle": {"link": "FloatTitle"},
    "TelescopeSelection": {"bg": "ui.selection", "bold": True},
    "TelescopeSelectionCaret": {"fg": "syntax.keyword", "bg": "ui.selection"},
    "TelescopeMatching": {"fg": "syntax.keyword", "bold": True},
    "TelescopePromptPrefix": {"fg": "syntax.keyword"},
    # nvim-treesitter-context. Its default links to NormalFloat, whose bg is the
    # cursor line's, so pinned scope lines looked like real buffer lines.
    # Italics mark them as pinned without adding another background shade.
    "TreesitterContext": {"fg": "ui.fg", "bg": "ui.context", "italic": True},
    "TreesitterContextLineNumber": {"fg": "ui.line_number", "bg": "ui.context", "italic": True},
    # nvim-cmp
    "CmpItemAbbr": {"fg": "ui.fg"},
    "CmpItemAbbrMatch": {"fg": "syntax.keyword", "bold": True},
    "CmpItemAbbrMatchFuzzy": {"fg": "syntax.keyword"},
    "CmpItemAbbrDeprecated": {"fg": "ui.fg_subtle", "strikethrough": True},
    "CmpItemMenu": {"fg": "ui.fg_muted"},
    "CmpItemKind": {"fg": "ui.fg_muted"},
    "CmpItemKindFunction": {"fg": "syntax.function"},
    "CmpItemKindMethod": {"fg": "syntax.function"},
    "CmpItemKindConstructor": {"fg": "syntax.type"},
    "CmpItemKindVariable": {"fg": "syntax.variable"},
    "CmpItemKindField": {"fg": "syntax.field"},
    "CmpItemKindProperty": {"fg": "syntax.field"},
    "CmpItemKindKeyword": {"fg": "syntax.keyword"},
    "CmpItemKindStruct": {"fg": "syntax.type"},
    "CmpItemKindClass": {"fg": "syntax.type"},
    "CmpItemKindInterface": {"fg": "syntax.type"},
    "CmpItemKindEnum": {"fg": "syntax.type"},
    "CmpItemKindEnumMember": {"fg": "syntax.constant"},
    "CmpItemKindConstant": {"fg": "syntax.constant"},
    "CmpItemKindModule": {"fg": "syntax.module"},
    "CmpItemKindSnippet": {"fg": "syntax.macro"},
    "CmpItemKindText": {"fg": "ui.fg_muted"},
    # leap.nvim
    "LeapMatch": {"fg": "syntax.keyword", "bold": True, "underline": True},
    "LeapLabel": {"fg": "ui.cursor_text", "bg": "syntax.keyword", "bold": True},
    "LeapBackdrop": {"fg": "ui.fg_subtle"},
    # vim-illuminate
    "IlluminatedWordText": {"link": "LspReferenceText"},
    "IlluminatedWordRead": {"link": "LspReferenceRead"},
    "IlluminatedWordWrite": {"link": "LspReferenceWrite"},
    # vim-matchup
    "MatchWord": {"link": "MatchParen"},
}

_NVIM_COLOR_KEYS = ("fg", "bg", "sp")


def _lua_value(v) -> str:
    if v is True:
        return "true"
    if v is False:
        return "false"
    return json.dumps(v)  # strings: JSON escaping is valid Lua for our values


def _nvim_spec(theme: Theme, spec: dict) -> str:
    parts = []
    for key, value in spec.items():
        if key in _NVIM_COLOR_KEYS:
            value = hx(theme, value)
        parts.append(f"{key} = {_lua_value(value)}")
    return "{ " + ", ".join(parts) + " }"


def build_nvim(theme: Theme) -> Output:
    lines = [
        f"-- {HEADER}",
        "-- Source: https://github.com/agrzeslak/myeyes",
        "",
        'vim.cmd("highlight clear")',
        'if vim.fn.exists("syntax_on") == 1 then',
        '\tvim.cmd("syntax reset")',
        "end",
        'vim.o.background = "light"',
        'vim.g.colors_name = "myeyes"',
        "",
        "local hl = vim.api.nvim_set_hl",
        "",
    ]
    for group, spec in NVIM_GROUPS.items():
        lines.append(f'hl(0, "{group}", {_nvim_spec(theme, spec)})')

    # `:terminal` buffers use these, mirroring the terminal emulator schemes.
    lines.append("")
    for i, name in enumerate(ANSI_ORDER):
        lines.append(f'vim.g.terminal_color_{i} = "{hx(theme, "ansi." + name)}"')
    return Output("colors/myeyes.lua", "\n".join(lines) + "\n")


# ==============================================================================
# lualine theme
# ==============================================================================

# Mode colours follow common convention (insert green, visual purple-ish,
# replace red) using myeyes accents. Section `a` is the mode pill, `b` a
# slightly raised surface, `c` the bar itself.
LUALINE_MODES = {
    "normal": "syntax.function",  # blue
    "insert": "diagnostic.ok",  # green
    "visual": "syntax.keyword",  # magenta
    "replace": "diagnostic.error",  # red
    "command": "diagnostic.warning",  # orange
    "terminal": "syntax.string",  # cyan
}


def build_lualine(theme: Theme) -> Output:
    b_bg, b_fg = hx(theme, "ui.selection"), hx(theme, "ui.fg_strong")
    c_bg, c_fg = hx(theme, "ui.statusline"), hx(theme, "ui.fg")
    pill_fg = hx(theme, "ui.cursor_text")
    lines = [f"-- {HEADER}", "", "return {"]
    for mode, role in LUALINE_MODES.items():
        lines += [
            f"\t{mode} = {{",
            f'\t\ta = {{ fg = "{pill_fg}", bg = "{hx(theme, role)}", gui = "bold" }},',
            f'\t\tb = {{ fg = "{b_fg}", bg = "{b_bg}" }},',
            f'\t\tc = {{ fg = "{c_fg}", bg = "{c_bg}" }},',
            "\t},",
        ]
    lines += [
        "\tinactive = {",
        f'\t\ta = {{ fg = "{hx(theme, "ui.fg_muted")}", bg = "{c_bg}", gui = "bold" }},',
        f'\t\tb = {{ fg = "{hx(theme, "ui.fg_muted")}", bg = "{c_bg}" }},',
        f'\t\tc = {{ fg = "{hx(theme, "ui.fg_muted")}", bg = "{c_bg}" }},',
        "\t},",
        "}",
    ]
    return Output("lua/lualine/themes/myeyes.lua", "\n".join(lines) + "\n")


# ==============================================================================
# tmux
# ==============================================================================


def build_tmux(theme: Theme) -> Output:
    c = lambda role: hx(theme, role)  # noqa: E731
    c_rgb = lambda role: ";".join(map(str, theme.role(role).rgb))  # noqa: E731
    body = f"""\
# {HEADER}
# Source with: source-file ~/.config/tmux/myeyes.conf

set-option -g status-style "fg={c('ui.fg')},bg={c('ui.statusline')}"
set-window-option -g window-status-style "fg={c('ui.fg_muted')},bg=default"
set-window-option -g window-status-current-style "fg={c('syntax.keyword')},bg=default,bold"
set-window-option -g window-status-activity-style "fg={c('diagnostic.warning')},bg=default"
set-window-option -g window-status-bell-style "fg={c('ui.cursor_text')},bg={c('diagnostic.error')}"

set-option -g pane-border-style "fg={c('ui.border')}"
set-option -g pane-active-border-style "fg={c('ui.float_border')}"

set-option -g message-style "fg={c('ui.fg_strong')},bg={c('ui.selection')}"
set-option -g message-command-style "fg={c('ui.fg_strong')},bg={c('ui.selection')}"

set-option -g display-panes-active-colour "{c('syntax.keyword')}"
set-option -g display-panes-colour "{c('ui.fg_muted')}"
set-window-option -g clock-mode-colour "{c('syntax.function')}"

# Faint text (SGR 2). Windows Terminal renders faint by halving the colour's
# brightness, which on a light background makes near-black text *darker*, so
# faint and normal text look identical (e.g. Claude Code's ghost suggestions).
# tmux emits faint via the terminfo `dim` capability, so for the terminal type
# Windows Terminal reports we redefine `dim` as "set foreground to the muted
# grey". Text with its own colour sets it after this and keeps that colour;
# default-coloured faint text renders muted. Alacritty has a native dim
# palette (see its theme), so it's left alone.
set-option -as terminal-overrides ',xterm-256color:dim=\\E[38;2;{c_rgb('ui.fg_muted')}m'

# Copy-mode selection and search matches.
set-window-option -g mode-style "fg={c('ui.selection_fg')},bg={c('ui.selection')}"
set-window-option -g copy-mode-match-style "bg={c('ui.search')}"
set-window-option -g copy-mode-current-match-style "bg={c('ui.search_current')}"
"""
    return Output("extras/tmux/myeyes.conf", body)


# ==============================================================================
# fzf
# ==============================================================================

# fzf has no theme files, only `--color` options, and defaults to a palette
# built for dark terminals. This is an options file for FZF_DEFAULT_OPTS_FILE,
# which fzf reads *before* FZF_DEFAULT_OPTS, so per-shell options (height,
# layout) stay in the environment variable. fzf.vim invokes the same binary
# and picks it up too.
#
# `bg:-1`/`gutter:-1` keep the terminal background, so fzf blends into
# whatever surface it runs on. Matches use the keyword magenta, matching
# Telescope and nvim-cmp.

FZF_COLORS = {
    "fg": "ui.fg",
    "bg": None,  # terminal default
    "hl": "syntax.keyword",
    "fg+": "ui.fg_strong",
    "bg+": "ui.selection",
    "hl+": "syntax.keyword",
    "gutter": None,
    "query": "ui.fg_strong",
    "prompt": "syntax.function",
    "pointer": "syntax.keyword",
    "marker": "diagnostic.ok",
    "spinner": "ui.fg_muted",
    "info": "ui.fg_muted",
    "header": "ui.fg_muted",
    "separator": "ui.border",
    "scrollbar": "ui.border",
    "border": "ui.float_border",
    "label": "ui.fg_muted",
}


def build_fzf(theme: Theme) -> Output:
    pairs = [f"{k}:{hx(theme, v) if v else -1}" for k, v in FZF_COLORS.items()]
    lines = [
        f"# {HEADER}",
        "# Use with: set -gx FZF_DEFAULT_OPTS_FILE ~/.config/fzf/myeyes.opts",
        # Base scheme first, so any element not listed below still gets
        # fzf's light-background defaults rather than its dark ones.
        "--color=light",
        f"--color={','.join(pairs)}",
    ]
    return Output("extras/fzf/myeyes.opts", "\n".join(lines) + "\n")


# ==============================================================================
# fish
# ==============================================================================

# fish 4.3+ theme file. No `[light]`/`[dark]` sections: a section-less theme
# applies whatever background fish detects, which is what we want for a
# single-variant theme. Colours are hex without `#`, as fish expects.


def build_fish(theme: Theme) -> Output:
    c = lambda role: hx(theme, role).lstrip("#")  # noqa: E731
    rows = {
        "fish_color_normal": c("ui.fg"),
        "fish_color_command": c("syntax.function"),
        "fish_color_keyword": c("syntax.keyword"),
        "fish_color_param": c("syntax.variable"),
        "fish_color_option": c("syntax.variable"),
        "fish_color_quote": c("syntax.string"),
        "fish_color_escape": c("syntax.escape"),
        "fish_color_redirection": c("syntax.operator"),
        "fish_color_operator": c("syntax.operator"),
        "fish_color_end": c("syntax.punctuation"),
        "fish_color_comment": c("syntax.comment"),
        "fish_color_error": c("diagnostic.error"),
        "fish_color_autosuggestion": c("ui.fg_subtle"),
        "fish_color_valid_path": "--underline",
        "fish_color_cwd": c("syntax.function"),
        "fish_color_cwd_root": c("diagnostic.error"),
        "fish_color_user": c("diagnostic.ok"),
        "fish_color_host": c("ui.fg"),
        "fish_color_host_remote": c("syntax.type"),
        "fish_color_status": c("diagnostic.error"),
        "fish_color_cancel": "-r",
        "fish_color_history_current": "--bold",
        "fish_color_selection": f"{c('ui.selection_fg')} --background={c('ui.selection')}",
        "fish_color_search_match": f"--background={c('ui.search')}",
        "fish_pager_color_completion": c("ui.fg"),
        "fish_pager_color_description": c("ui.fg_muted"),
        "fish_pager_color_prefix": f"{c('syntax.keyword')} --bold",
        "fish_pager_color_progress": f"{c('ui.fg_strong')} --background={c('ui.selection')}",
        "fish_pager_color_selected_background": f"--background={c('ui.selection')}",
    }
    lines = [
        "# name: myeyes",
        f"# {HEADER}",
        f"# preferred_background: {c('ui.bg')}",
        "",
    ]
    lines += [f"{k} {v}" for k, v in rows.items()]
    return Output("extras/fish/myeyes.theme", "\n".join(lines) + "\n")


# ==============================================================================
# Codex CLI (.tmTheme)
# ==============================================================================

# Codex highlights code with syntect, which consumes TextMate themes. TextMate
# scopes are coarser than tree-sitter captures; each rule maps the closest
# scope family onto a role. The same file works for bat and Sublime Text.
#
# TODO: Sublime's Rust grammar scopes primitive types (`u32`, `str`) as
# `storage.type`, the same as `let`, so in Codex/bat they take the storage
# (keyword) colour rather than the type colour. No scope separates them.

TMTHEME_RULES: list[tuple[str, str, str, str]] = [
    # (name, scope selector, role, font style)
    ("Comment", "comment, punctuation.definition.comment", "syntax.comment", ""),
    ("String", "string, punctuation.definition.string", "syntax.string", ""),
    ("Escape", "constant.character.escape, constant.other.placeholder", "syntax.escape", ""),
    ("Number", "constant.numeric", "syntax.number", ""),
    ("Constant", "constant.language, constant.other, support.constant", "syntax.constant", ""),
    ("Keyword", "keyword, keyword.control, keyword.other", "syntax.keyword", ""),
    ("Storage", "storage, storage.type, storage.modifier", "syntax.storage", ""),
    ("Operator", "keyword.operator", "syntax.operator", ""),
    ("Function", "entity.name.function, support.function, meta.function-call", "syntax.function", ""),
    ("Macro", "entity.name.function.macro, support.macro, meta.macro", "syntax.macro", ""),
    ("Type", "entity.name.type, entity.name.class, entity.name.struct, entity.name.enum, support.type, support.class", "syntax.type", ""),
    ("Lifetime", "storage.modifier.lifetime, entity.name.lifetime", "syntax.lifetime", ""),
    ("Attribute", "meta.annotation, meta.attribute, entity.other.attribute-name", "syntax.attribute", ""),
    ("Module", "entity.name.namespace, entity.name.module", "syntax.module", ""),
    ("Variable", "variable, variable.parameter", "syntax.variable", ""),
    ("Punctuation", "punctuation", "syntax.punctuation", ""),
    ("Tag", "entity.name.tag", "syntax.keyword", ""),
    ("Heading", "markup.heading, entity.name.section", "ui.fg_strong", "bold"),
    ("Bold", "markup.bold", "ui.fg_strong", "bold"),
    ("Italic", "markup.italic", "ui.fg", "italic"),
    ("Link", "markup.underline.link", "ui.link", "underline"),
    ("Raw", "markup.raw", "syntax.string", ""),
    ("Inserted", "markup.inserted", "diagnostic.diff_add", ""),
    ("Deleted", "markup.deleted", "diagnostic.diff_delete", ""),
    ("Changed", "markup.changed", "diagnostic.diff_change", ""),
    ("Invalid", "invalid", "diagnostic.error", ""),
]


def _plist_dict(entries: dict[str, str], indent: str) -> list[str]:
    out = [f"{indent}<dict>"]
    for k, v in entries.items():
        out.append(f"{indent}\t<key>{xml_escape(k)}</key>")
        out.append(f"{indent}\t<string>{xml_escape(v)}</string>")
    out.append(f"{indent}</dict>")
    return out


def build_tmtheme(theme: Theme) -> Output:
    settings = {
        "background": hx(theme, "ui.bg"),
        "foreground": hx(theme, "ui.fg"),
        "caret": hx(theme, "ui.cursor"),
        "selection": hx(theme, "ui.selection"),
        "lineHighlight": hx(theme, "ui.cursorline"),
        "invisibles": hx(theme, "ui.fg_subtle"),
        "gutterForeground": hx(theme, "ui.line_number"),
    }
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        f"<!-- {HEADER} -->",
        '<plist version="1.0">',
        "<dict>",
        "\t<key>name</key>",
        "\t<string>myeyes</string>",
        "\t<key>settings</key>",
        "\t<array>",
        "\t\t<dict>",
        "\t\t\t<key>settings</key>",
        *_plist_dict(settings, "\t\t\t"),
        "\t\t</dict>",
    ]
    for name, scope, role, style in TMTHEME_RULES:
        rule = {"foreground": hx(theme, role)}
        if style:
            rule["fontStyle"] = style
        lines += [
            "\t\t<dict>",
            "\t\t\t<key>name</key>",
            f"\t\t\t<string>{xml_escape(name)}</string>",
            "\t\t\t<key>scope</key>",
            f"\t\t\t<string>{xml_escape(scope)}</string>",
            "\t\t\t<key>settings</key>",
            *_plist_dict(rule, "\t\t\t"),
            "\t\t</dict>",
        ]
    lines += ["\t</array>", "</dict>", "</plist>"]
    return Output("extras/codex/myeyes.tmTheme", "\n".join(lines) + "\n")


# ==============================================================================
# Claude Code custom theme
# ==============================================================================

# Claude Code reads `~/.claude/themes/<slug>.json`: a base preset plus token
# overrides. Token names were taken from the built-in `light` theme in the
# installed binary (v2.1.283, re-checked v2.1.292); unknown tokens are ignored by Claude Code, so a
# rename upstream degrades to the base preset rather than breaking.
#
# Intentionally not overridden: the `rainbow_*` tokens (decorative, used for
# celebratory effects) and `clawd_*` mascot colours beyond the body.

CLAUDE_TOKENS: dict[str, str] = {
    "text": "ui.fg",
    "inverseText": "ui.cursor_text",
    "inactive": "ui.fg_muted",
    "inactiveShimmer": "ui.fg_subtle",
    # `subtle` carries readable hint text, so it gets the muted (5:1) grey
    # rather than the faint one, which is meant for non-text decoration.
    "subtle": "ui.fg_muted",
    "promptBorder": "ui.float_border",
    "promptBorderShimmer": "ui.fg_muted",
    # Brand accent: Claude's terracotta maps onto our orange.
    "claude": "palette.orange",
    "claudeShimmer": "palette.orange_bright",
    "clawd_body": "palette.orange",
    "briefLabelClaude": "palette.orange",
    "claudeBlue_FOR_SYSTEM_SPINNER": "ansi.blue",
    "claudeBlueShimmer_FOR_SYSTEM_SPINNER": "ansi.bright_blue",
    # `permission` is also the inline-code (`codespan`) colour in rendered
    # markdown, which is where it's seen most, so it follows the brand orange.
    # Permission prompts share it; Claude Code offers no separate token.
    "permission": "palette.orange",
    "permissionShimmer": "palette.orange_bright",
    "suggestion": "ansi.blue",
    "remember": "ansi.blue",
    "ide": "ansi.blue",
    "professionalBlue": "ansi.blue",
    "briefLabelYou": "ansi.blue",
    "rate_limit_fill": "ansi.blue",
    "rate_limit_empty": "ui.border",
    "planMode": "ansi.cyan",
    "background": "ansi.cyan",  # a teal accent token, not the page background
    "autoAccept": "syntax.keyword",
    "autoAcceptShimmer": "palette.magenta_bright",  # added in v2.1.292
    "skill": "syntax.keyword",
    "merged": "syntax.keyword",
    "effortUltra": "syntax.keyword",
    "bashBorder": "syntax.keyword",
    "success": "diagnostic.ok",
    "error": "diagnostic.error",
    "warning": "ansi.yellow",
    "warningShimmer": "ansi.bright_yellow",
    "fastMode": "diagnostic.warning",
    "fastModeShimmer": "palette.orange_bright",
    "chromeYellow": "ansi.bright_yellow",
    # Diffs: line tints, paler tints for context, and bright accents for
    # word-level changes and the "+N/-N" counters (used as text colour there).
    "diffAdded": "diagnostic.diff_add_word_bg",
    "diffRemoved": "diagnostic.diff_delete_word_bg",
    "diffAddedDimmed": "diagnostic.diff_add_bg",
    "diffRemovedDimmed": "diagnostic.diff_delete_bg",
    "diffAddedWord": "ansi.bright_green",
    "diffRemovedWord": "ansi.bright_red",
    # Surfaces.
    "userMessageBackground": "ui.cursorline",
    "userMessageBackgroundHover": "ui.selection",
    "composerSidebarBackground": "ui.cursorline",
    "bashMessageBackgroundColor": "ui.cursorline",
    "memoryBackgroundColor": "diagnostic.info_bg",
    "selectionBg": "ui.selection",
    "clawd_background": "ui.fg_strong",
    # Subagent colour coding.
    "red_FOR_SUBAGENTS_ONLY": "ansi.red",
    "blue_FOR_SUBAGENTS_ONLY": "ansi.blue",
    "green_FOR_SUBAGENTS_ONLY": "ansi.green",
    "yellow_FOR_SUBAGENTS_ONLY": "ansi.yellow",
    "purple_FOR_SUBAGENTS_ONLY": "syntax.number",  # violet
    "orange_FOR_SUBAGENTS_ONLY": "diagnostic.warning",
    "pink_FOR_SUBAGENTS_ONLY": "ansi.magenta",
    "cyan_FOR_SUBAGENTS_ONLY": "ansi.cyan",
}


def build_claude(theme: Theme) -> Output:
    doc = {
        "name": "myeyes",
        "base": "light",
        "overrides": {token: hx(theme, role) for token, role in CLAUDE_TOKENS.items()},
    }
    return Output("extras/claude/myeyes.json", json.dumps(doc, indent=2) + "\n")


# ==============================================================================
# Terminal emulators
# ==============================================================================

ANSI_ORDER = [
    "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white",
    "bright_black", "bright_red", "bright_green", "bright_yellow",
    "bright_blue", "bright_magenta", "bright_cyan", "bright_white",
]  # fmt: skip


def windows_terminal_scheme(theme: Theme) -> dict[str, str]:
    # Windows Terminal calls magenta "purple" and uses camelCase brights.
    def wt_name(ansi: str) -> str:
        bright, _, base = ansi.rpartition("_")
        base = "purple" if base == "magenta" else base
        return f"bright{base.capitalize()}" if bright else base

    scheme = {
        "name": "myeyes",
        "background": hx(theme, "ui.bg"),
        "foreground": hx(theme, "ui.fg"),
        "cursorColor": hx(theme, "ui.cursor"),
        "selectionBackground": hx(theme, "ui.selection"),
    }
    scheme |= {wt_name(n): hx(theme, f"ansi.{n}") for n in ANSI_ORDER}
    return scheme


def build_windows_terminal(theme: Theme) -> Output:
    return Output(
        "extras/windows-terminal/myeyes.json",
        json.dumps(windows_terminal_scheme(theme), indent=4) + "\n",
    )


def build_alacritty(theme: Theme) -> Output:
    c = lambda role: hx(theme, role)  # noqa: E731
    lines = [
        f"# {HEADER}",
        '# Use with: general.import = ["~/.config/alacritty/myeyes.toml"]',
        "",
        "[colors.primary]",
        f'background = "{c("ui.bg")}"',
        f'foreground = "{c("ui.fg")}"',
        # Faint text: Alacritty's default darkens colours, which on a light
        # background makes faint text indistinguishable from normal text.
        f'dim_foreground = "{c("ui.fg_muted")}"',
        "",
        "[colors.cursor]",
        f'cursor = "{c("ui.cursor")}"',
        f'text = "{c("ui.cursor_text")}"',
        "",
        "[colors.selection]",
        f'background = "{c("ui.selection")}"',
        f'text = "{c("ui.selection_fg")}"',
        "",
        "[colors.search.matches]",
        f'background = "{c("ui.search")}"',
        f'foreground = "{c("ui.fg")}"',
        "",
        "[colors.search.focused_match]",
        f'background = "{c("ui.search_current")}"',
        f'foreground = "{c("ui.fg_strong")}"',
    ]
    # Dim palette: on a light background "fainter" means lighter, which is
    # what the bright variants already are.
    for section, prefix in (("normal", ""), ("bright", "bright_"), ("dim", "bright_")):
        lines += ["", f"[colors.{section}]"]
        for name in ANSI_ORDER[:8]:
            lines.append(f'{name} = "{c(f"ansi.{prefix}{name}")}"')
    return Output("extras/alacritty/myeyes.toml", "\n".join(lines) + "\n")


BUILDERS = [
    build_nvim,
    build_lualine,
    build_tmux,
    build_fzf,
    build_fish,
    build_tmtheme,
    build_claude,
    build_windows_terminal,
    build_alacritty,
]


# ==============================================================================
# Install
# ==============================================================================

# Copy targets into the dotfile locations their programs read. Neovim and
# lualine are not copied: the repo itself is the Neovim plugin.
#
# Directories that do not exist are skipped rather than created, so running
# `--install` on a machine without (say) Alacritty doesn't litter $HOME.

HOME = Path.home()
INSTALL_TARGETS = {
    "extras/tmux/myeyes.conf": HOME / ".config/tmux/myeyes.conf",
    "extras/fish/myeyes.theme": HOME / ".config/fish/themes/myeyes.theme",
    "extras/fzf/myeyes.opts": HOME / ".config/fzf/myeyes.opts",
    "extras/codex/myeyes.tmTheme": HOME / ".codex/themes/myeyes.tmTheme",
    "extras/claude/myeyes.json": HOME / ".claude/themes/myeyes.json",
    "extras/alacritty/myeyes.toml": HOME / ".config/alacritty/myeyes.toml",
}

# Created on demand because their parent program directory is known to exist
# whenever the program is installed.
CREATE_PARENTS = {".config/tmux", ".config/fzf", ".config/fish/themes", ".codex/themes", ".claude/themes"}

WINDOWS_TERMINAL_GLOB = (
    "/mnt/c/Users/*/AppData/Local/Packages/"
    "Microsoft.WindowsTerminal_*/LocalState/settings.json"
)


def install(theme: Theme):
    for src, dest in INSTALL_TARGETS.items():
        rel_parent = str(dest.parent.relative_to(HOME))
        program_dir_exists = dest.parent.exists() or (
            rel_parent in CREATE_PARENTS and dest.parent.parent.exists()
        )
        if not program_dir_exists:
            print(f"skip    {dest} (no {dest.parent})")
            continue
        dest.parent.mkdir(exist_ok=True)
        shutil.copyfile(REPO / src, dest)
        print(f"install {dest}")

    # Windows Terminal: replace (or add) only the `myeyes` scheme entry, keeping
    # the rest of settings.json intact. Selecting the scheme is left to the
    # user's profile settings, so reinstalling after a tweak never overrides
    # deliberate per-profile choices.
    import glob

    user = Path(HOME).name
    for path in map(Path, glob.glob(WINDOWS_TERMINAL_GLOB)):
        if path.parts[4] != user:  # /mnt/c/Users/<user>/...
            continue
        raw = path.read_text(encoding="utf-8-sig")
        try:
            settings = json.loads(raw)
        except json.JSONDecodeError:
            # settings.json may contain comments (JSONC); rather than risk a
            # lossy rewrite, leave it to be edited by hand.
            print(f"skip    {path} (not strict JSON; add extras/windows-terminal/myeyes.json by hand)")
            continue
        scheme = windows_terminal_scheme(theme)
        if scheme in settings.get("schemes", []):
            print(f"same    {path} (scheme 'myeyes' up to date)")
            continue
        # Back up once, before the first ever myeyes edit, and never overwrite
        # it: a per-run backup would replace the original after a second tweak.
        backup = path.with_name("settings.json.pre-myeyes.bak")
        if not backup.exists():
            shutil.copyfile(path, backup)
        schemes = [s for s in settings.get("schemes", []) if s.get("name") != "myeyes"]
        schemes.append(scheme)
        settings["schemes"] = schemes
        path.write_text(json.dumps(settings, indent=4, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"install {path} (scheme 'myeyes'; original kept at {backup.name})")


# ==============================================================================
# Entry point
# ==============================================================================


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true", help="fail if generated files are stale")
    p.add_argument("--install", action="store_true", help="copy extras into dotfile locations")
    args = p.parse_args()

    theme = load_theme()
    outputs = [build(theme) for build in BUILDERS]

    if args.check:
        stale = [o.path for o in outputs if not (REPO / o.path).exists()
                 or (REPO / o.path).read_text() != o.content]
        for path in stale:
            print(f"stale   {path}")
        sys.exit(1 if stale else 0)

    for o in outputs:
        dest = REPO / o.path
        dest.parent.mkdir(parents=True, exist_ok=True)
        changed = not dest.exists() or dest.read_text() != o.content
        dest.write_text(o.content)
        print(f"{'wrote' if changed else 'same '}   {o.path}")

    if args.install:
        install(theme)


if __name__ == "__main__":
    main()
